# Generated by Django 4.2.3 on 2023-08-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=10, unique=True)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cabin')),
                ('seats', models.ManyToManyField(to='home.seat')),
            ],
        ),
    ]
